# Generated by Django 3.2.3 on 2021-05-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort_api', '0005_alter_urlshort_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='full_url',
            field=models.URLField(verbose_name='Ссылка'),
        ),
    ]
