# Generated by Django 3.2.3 on 2021-05-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort_api', '0006_alter_urlshort_full_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Создан'),
        ),
    ]
