# Generated by Django 3.2.3 on 2021-05-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort_api', '0007_alter_urlshort_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='user_session_key',
            field=models.CharField(max_length=70, verbose_name='Ключ сессии пользователя'),
        ),
    ]
