# Generated by Django 3.2.3 on 2021-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort_api', '0008_alter_urlshort_user_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='hash',
            field=models.CharField(max_length=128, unique=True, verbose_name='Хэш ссылки'),
        ),
    ]
